language: cpp

env:
  - COVERALLS_REPO_TOKEN=KPDH1Nr3wpZZiXko19X4tkSjcvBUlNoSH

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install lcov; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt55base; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PATH:/opt/qt55/bin; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source qt55-env.sh; fi

  - cd CPPWebFramework
  - qmake UnitTests.pro
  - make -j 8
  - ./UnitTests
  - rm *tst_*
  - rm main*
  - then rm moc
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --exclude lib --exclude tests --exclude *Qt* --exclude */usr/* --gcov-options '\-lp'; fi
  - make clean

  - qmake CPPWebFramework.pro
  - make -j 8
  - sudo make install

  - cd ..
  - cd examples

  - cd HelloWorld
  - qmake HelloWorld.pro
  - make -j 8

  - cd ..
  - cd ShowFile
  - qmake ShowFile.pro
  - make -j 8

  - cd ..
  - cd SaveFiles
  - qmake SaveFiles.pro
  - make -j 8

  - cd ..
  - cd Sessions
  - qmake Sessions.pro
  - make -j 8

  - cd ..
  - cd Filters
  - qmake Filters.pro
  - make -j 8

  - cd ..
  - cd CSTLOutExample
  - qmake CSTLOutExample.pro
  - make

  - cd ..
  - cd CSTLForExample
  - qmake CSTLForExample.pro
  - make -j 8

  - cd ..
  - cd CSTLIfExample
  - qmake CSTLIfExample.pro
  - make -j 8

  - cd ..
  - cd FillObjectBMI
  - qmake FillObjectBMI.pro
  - make -j 8

  - cd ..
  - cd CSTLImportExample
  - qmake CSTLImportExample.pro
  - make -j 8

  - cd ..
  - cd WebServices
  - qmake WebServices.pro
  - make -j 8

  - cd ..
  - cd CRUDRestWebService
  - qmake CRUDRestWebService.pro
  - make -j 8

  - cd ..
  - cd HelloWorldFilter
  - qmake HelloWorldFilter.pro
  - make -j 8

  - cd ..
  - cd HelloMVC
  - qmake HelloMVC.pro
  - make -j 8

  - cd ..
  - cd RESTWebService
  - qmake RESTWebService.pro
  - make -j 8

