language: cpp

env:
  - COVERALLS_REPO_TOKEN=KPDH1Nr3wpZZiXko19X4tkSjcvBUlNoSH

compiler:
  - gcc

sudo: required
dist: trusty


before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install lcov
  - sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt57base

script:
  - source /opt/qt57/bin/qt57-env.sh;

  - cd CPPWebFramework
  - /opt/qt57/bin/qmake CPPWebFramework.pro
  - make -j 8
  - sudo make install

  - /opt/qt57/bin/qmake UnitTests.pro
  - make -j 8
  - ./UnitTests
  - rm *tst_*
  - rm main*
  - rm moc*
  - coveralls --exclude lib --exclude tests --exclude *Qt* --exclude */usr/* --gcov-options '\-lp'

  - cd ..
  - cd examples/HelloWorld
  - /opt/qt57/bin/qmake HelloWorld.pro
  - make -j 8

  - cd ..
  - cd ShowFile
  - /opt/qt57/bin/qmake ShowFile.pro
  - make -j 8

  - cd ..
  - cd SaveFiles
  - /opt/qt57/bin/qmake SaveFiles.pro
  - make -j 8

  - cd ..
  - cd Sessions
  - /opt/qt57/bin/qmake Sessions.pro
  - make -j 8

  - cd ..
  - cd Filters
  - /opt/qt57/bin/qmake Filters.pro
  - make -j 8

  - cd ..
  - cd CSTLOutExample
  - /opt/qt57/bin/qmake CSTLOutExample.pro
  - make

  - cd ..
  - cd CSTLForExample
  - /opt/qt57/bin/qmake CSTLForExample.pro
  - make -j 8

  - cd ..
  - cd CSTLIfExample
  - /opt/qt57/bin/qmake CSTLIfExample.pro
  - make -j 8

  - cd ..
  - cd FillObjectBMI
  - /opt/qt57/bin/qmake FillObjectBMI.pro
  - make -j 8

  - cd ..
  - cd CSTLImportExample
  - /opt/qt57/bin/qmake CSTLImportExample.pro
  - make -j 8

  - cd ..
  - cd WebServices
  - /opt/qt57/bin/qmake WebServices.pro
  - make -j 8
